name: sphinx_furo
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core functionality
  - python=3.11
  - ipython
  # sphinx
  - sphinx=5.3.0 # sphinx-design currently requires sphinx[version>=2,<5]
  - furo=2023.3.27 # website theme
  - myst-parser=0.19.1 # Markdown support
  - sphinx-autobuild=2021.3.14 # live-html support
  - sphinx-autoapi=2.1.0 # to build docs from source code instead of package import
  - sphinx-click==4.1.0 # to build docs from click command line interface